# Runs lint, test, builds the nightly build (staging) version of the Android APK & iOS IPA, and deploys it to Firebase app distribution
name: deploy-staging

on: push

jobs:
  set-env-short-sha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env: 
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env: 
          SHA: ${{ env.SHA }}
  use-short-sha:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SHA
        env: 
          SHA: ${{ job.set-env-short-sha.short-sha.outputs.sha }}
      - run: echo $SHA
        env: 
          SHA: ${{ env.SHA }}
